# PostgreSQL
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/payments}
spring.datasource.username=${DB_USERNAME:payments}
spring.datasource.password=${DB_PASSWORD:payments}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.hikari.maximum-pool-size=5
spring.datasource.hikari.minimum-idle=1

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Redis
spring.data.redis.host=${REDIS_HOST:localhost}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.timeout=2000ms

# Cache
spring.cache.type=redis

# Logging
logging.level.com.billing.payments_core_api=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

# Stripe
stripe.api.key=${STRIPE_API_KEY:sk_test_replace_me}
